# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1600, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1600, 900))
        MainWindow.setAcceptDrops(False)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(49, 72, 80);")
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_title = QtWidgets.QFrame(self.centralwidget)
        self.frame_title.setGeometry(QtCore.QRect(0, 0, 1600, 80))
        self.frame_title.setStyleSheet("background-color: rgb(30, 44, 49);")
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        self.label_title.setGeometry(QtCore.QRect(680, 0, 240, 80))
        self.label_title.setStyleSheet("font: 63 40pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setWordWrap(False)
        self.label_title.setObjectName("label_title")
        self.frame_options = QtWidgets.QFrame(self.centralwidget)
        self.frame_options.setGeometry(QtCore.QRect(0, 80, 1600, 40))
        self.frame_options.setStyleSheet("background-color: rgb(38, 55, 62);")
        self.frame_options.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_options.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_options.setObjectName("frame_options")
        self.button_warframe = QtWidgets.QPushButton(self.frame_options)
        self.button_warframe.setGeometry(QtCore.QRect(520, 0, 80, 36))
        self.button_warframe.setStyleSheet("QPushButton{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(38, 55, 62);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(30, 47, 54);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(22, 39, 46);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}")
        self.button_warframe.setObjectName("button_warframe")
        self.button_primary = QtWidgets.QPushButton(self.frame_options)
        self.button_primary.setGeometry(QtCore.QRect(640, 0, 80, 36))
        self.button_primary.setStyleSheet("QPushButton{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(38, 55, 62);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(30, 47, 54);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(22, 39, 46);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}")
        self.button_primary.setObjectName("button_primary")
        self.button_secondary = QtWidgets.QPushButton(self.frame_options)
        self.button_secondary.setGeometry(QtCore.QRect(760, 0, 80, 36))
        self.button_secondary.setStyleSheet("QPushButton{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(38, 55, 62);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(30, 47, 54);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(22, 39, 46);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}")
        self.button_secondary.setObjectName("button_secondary")
        self.button_melee = QtWidgets.QPushButton(self.frame_options)
        self.button_melee.setGeometry(QtCore.QRect(880, 0, 80, 36))
        self.button_melee.setStyleSheet("QPushButton{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(38, 55, 62);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(30, 47, 54);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(22, 39, 46);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}")
        self.button_melee.setObjectName("button_melee")
        self.button_clearPage = QtWidgets.QPushButton(self.frame_options)
        self.button_clearPage.setGeometry(QtCore.QRect(100, 0, 80, 36))
        self.button_clearPage.setStyleSheet("QPushButton{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(38, 55, 62);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(30, 47, 54);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(22, 39, 46);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}")
        self.button_clearPage.setObjectName("button_clearPage")
        self.button_clearAll = QtWidgets.QPushButton(self.frame_options)
        self.button_clearAll.setGeometry(QtCore.QRect(10, 0, 80, 36))
        self.button_clearAll.setStyleSheet("QPushButton{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(38, 55, 62);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(30, 47, 54);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(22, 39, 46);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}")
        self.button_clearAll.setObjectName("button_clearAll")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 120, 1600, 780))
        self.stackedWidget.setAcceptDrops(False)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_warframe = QtWidgets.QWidget()
        self.page_warframe.setObjectName("page_warframe")
        self.label_warframe = QtWidgets.QLabel(self.page_warframe)
        self.label_warframe.setGeometry(QtCore.QRect(500, 0, 600, 60))
        self.label_warframe.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.label_warframe.setAlignment(QtCore.Qt.AlignCenter)
        self.label_warframe.setObjectName("label_warframe")
        self.line_warframeSelect = QtWidgets.QLineEdit(self.page_warframe)
        self.line_warframeSelect.setGeometry(QtCore.QRect(460, 60, 680, 31))
        self.line_warframeSelect.setAutoFillBackground(False)
        self.line_warframeSelect.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px\n"
"")
        self.line_warframeSelect.setText("")
        self.line_warframeSelect.setAlignment(QtCore.Qt.AlignCenter)
        self.line_warframeSelect.setObjectName("line_warframeSelect")
        self.label_warframeMiddle = QtWidgets.QLabel(self.page_warframe)
        self.label_warframeMiddle.setGeometry(QtCore.QRect(510, 110, 580, 480))
        self.label_warframeMiddle.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(49, 72, 80);\n"
"color: rgb(180, 180, 180);\n"
"padding: 8px")
        self.label_warframeMiddle.setText("")
        self.label_warframeMiddle.setScaledContents(True)
        self.label_warframeMiddle.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_warframeMiddle.setWordWrap(True)
        self.label_warframeMiddle.setObjectName("label_warframeMiddle")
        self.label_warframeMastery = QtWidgets.QLabel(self.page_warframe)
        self.label_warframeMastery.setGeometry(QtCore.QRect(60, 590, 1480, 80))
        self.label_warframeMastery.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(49, 72, 80);\n"
"color: rgb(180, 180, 180);")
        self.label_warframeMastery.setText("")
        self.label_warframeMastery.setAlignment(QtCore.Qt.AlignCenter)
        self.label_warframeMastery.setObjectName("label_warframeMastery")
        self.label_warframeLeft = QtWidgets.QLabel(self.page_warframe)
        self.label_warframeLeft.setGeometry(QtCore.QRect(60, 110, 450, 480))
        self.label_warframeLeft.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_warframeLeft.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(49, 72, 80);\n"
"color: rgb(180, 180, 180);\n"
"padding: 8px\n"
"")
        self.label_warframeLeft.setText("")
        self.label_warframeLeft.setScaledContents(True)
        self.label_warframeLeft.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_warframeLeft.setWordWrap(True)
        self.label_warframeLeft.setObjectName("label_warframeLeft")
        self.label_warframeRight = QtWidgets.QLabel(self.page_warframe)
        self.label_warframeRight.setGeometry(QtCore.QRect(1090, 110, 450, 480))
        self.label_warframeRight.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(49, 72, 80);\n"
"color: rgb(180, 180, 180);\n"
"padding: 8px")
        self.label_warframeRight.setText("")
        self.label_warframeRight.setScaledContents(True)
        self.label_warframeRight.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_warframeRight.setWordWrap(True)
        self.label_warframeRight.setObjectName("label_warframeRight")
        self.warframe_normalPicture = QtWidgets.QLabel(self.page_warframe)
        self.warframe_normalPicture.setGeometry(QtCore.QRect(195, 340, 180, 200))
        self.warframe_normalPicture.setAutoFillBackground(False)
        self.warframe_normalPicture.setStyleSheet("font: 63 16pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.warframe_normalPicture.setText("")
        self.warframe_normalPicture.setScaledContents(True)
        self.warframe_normalPicture.setAlignment(QtCore.Qt.AlignCenter)
        self.warframe_normalPicture.setObjectName("warframe_normalPicture")
        self.warframe_primePicture = QtWidgets.QLabel(self.page_warframe)
        self.warframe_primePicture.setGeometry(QtCore.QRect(1225, 340, 180, 200))
        self.warframe_primePicture.setAutoFillBackground(False)
        self.warframe_primePicture.setStyleSheet("font: 63 16pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.warframe_primePicture.setText("")
        self.warframe_primePicture.setScaledContents(True)
        self.warframe_primePicture.setAlignment(QtCore.Qt.AlignCenter)
        self.warframe_primePicture.setObjectName("warframe_primePicture")
        self.warframe_bpPicture = QtWidgets.QLabel(self.page_warframe)
        self.warframe_bpPicture.setGeometry(QtCore.QRect(530, 440, 120, 140))
        self.warframe_bpPicture.setAutoFillBackground(False)
        self.warframe_bpPicture.setStyleSheet("font: 63 11pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.warframe_bpPicture.setText("")
        self.warframe_bpPicture.setScaledContents(True)
        self.warframe_bpPicture.setAlignment(QtCore.Qt.AlignCenter)
        self.warframe_bpPicture.setObjectName("warframe_bpPicture")
        self.warframe_neuropticPicture = QtWidgets.QLabel(self.page_warframe)
        self.warframe_neuropticPicture.setGeometry(QtCore.QRect(670, 440, 120, 140))
        self.warframe_neuropticPicture.setAutoFillBackground(False)
        self.warframe_neuropticPicture.setStyleSheet("font: 63 11pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.warframe_neuropticPicture.setText("")
        self.warframe_neuropticPicture.setScaledContents(True)
        self.warframe_neuropticPicture.setAlignment(QtCore.Qt.AlignCenter)
        self.warframe_neuropticPicture.setObjectName("warframe_neuropticPicture")
        self.warframe_chassisPicture = QtWidgets.QLabel(self.page_warframe)
        self.warframe_chassisPicture.setGeometry(QtCore.QRect(810, 440, 120, 140))
        self.warframe_chassisPicture.setAutoFillBackground(False)
        self.warframe_chassisPicture.setStyleSheet("font: 63 11pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.warframe_chassisPicture.setText("")
        self.warframe_chassisPicture.setScaledContents(True)
        self.warframe_chassisPicture.setAlignment(QtCore.Qt.AlignCenter)
        self.warframe_chassisPicture.setObjectName("warframe_chassisPicture")
        self.warframe_systemPicture = QtWidgets.QLabel(self.page_warframe)
        self.warframe_systemPicture.setGeometry(QtCore.QRect(950, 440, 120, 140))
        self.warframe_systemPicture.setAutoFillBackground(False)
        self.warframe_systemPicture.setStyleSheet("font: 63 11pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.warframe_systemPicture.setText("")
        self.warframe_systemPicture.setScaledContents(True)
        self.warframe_systemPicture.setAlignment(QtCore.Qt.AlignCenter)
        self.warframe_systemPicture.setObjectName("warframe_systemPicture")
        self.stackedWidget.addWidget(self.page_warframe)
        self.page_primary = QtWidgets.QWidget()
        self.page_primary.setObjectName("page_primary")
        self.label_primary = QtWidgets.QLabel(self.page_primary)
        self.label_primary.setGeometry(QtCore.QRect(500, 0, 600, 60))
        self.label_primary.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.label_primary.setAlignment(QtCore.Qt.AlignCenter)
        self.label_primary.setObjectName("label_primary")
        self.line_primarySelect = QtWidgets.QLineEdit(self.page_primary)
        self.line_primarySelect.setGeometry(QtCore.QRect(460, 60, 680, 31))
        self.line_primarySelect.setAutoFillBackground(False)
        self.line_primarySelect.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px\n"
"")
        self.line_primarySelect.setText("")
        self.line_primarySelect.setAlignment(QtCore.Qt.AlignCenter)
        self.line_primarySelect.setObjectName("line_primarySelect")
        self.label_primaryMiddle = QtWidgets.QLabel(self.page_primary)
        self.label_primaryMiddle.setGeometry(QtCore.QRect(510, 190, 580, 400))
        self.label_primaryMiddle.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(49, 72, 80);\n"
"color: rgb(180, 180, 180);\n"
"padding: 8px")
        self.label_primaryMiddle.setText("")
        self.label_primaryMiddle.setScaledContents(True)
        self.label_primaryMiddle.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_primaryMiddle.setWordWrap(True)
        self.label_primaryMiddle.setObjectName("label_primaryMiddle")
        self.label_primaryRight = QtWidgets.QLabel(self.page_primary)
        self.label_primaryRight.setGeometry(QtCore.QRect(1090, 190, 450, 400))
        self.label_primaryRight.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(49, 72, 80);\n"
"color: rgb(180, 180, 180);\n"
"padding: 8px")
        self.label_primaryRight.setText("")
        self.label_primaryRight.setScaledContents(True)
        self.label_primaryRight.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_primaryRight.setWordWrap(True)
        self.label_primaryRight.setObjectName("label_primaryRight")
        self.label_primaryLeft = QtWidgets.QLabel(self.page_primary)
        self.label_primaryLeft.setGeometry(QtCore.QRect(60, 190, 450, 400))
        self.label_primaryLeft.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(49, 72, 80);\n"
"color: rgb(180, 180, 180);\n"
"padding: 8px")
        self.label_primaryLeft.setText("")
        self.label_primaryLeft.setScaledContents(True)
        self.label_primaryLeft.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_primaryLeft.setWordWrap(True)
        self.label_primaryLeft.setObjectName("label_primaryLeft")
        self.label_primaryMastery = QtWidgets.QLabel(self.page_primary)
        self.label_primaryMastery.setGeometry(QtCore.QRect(60, 590, 1480, 80))
        self.label_primaryMastery.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(49, 72, 80);\n"
"color: rgb(180, 180, 180);")
        self.label_primaryMastery.setText("")
        self.label_primaryMastery.setAlignment(QtCore.Qt.AlignCenter)
        self.label_primaryMastery.setObjectName("label_primaryMastery")
        self.list_primaryVariant = QtWidgets.QTreeWidget(self.page_primary)
        self.list_primaryVariant.setGeometry(QtCore.QRect(50, 20, 331, 151))
        self.list_primaryVariant.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"border-radius: 10px")
        self.list_primaryVariant.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list_primaryVariant.setAlternatingRowColors(False)
        self.list_primaryVariant.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.list_primaryVariant.setObjectName("list_primaryVariant")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.list_primaryVariant.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_primaryVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_primaryVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_primaryVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_primaryVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_primaryVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_primaryVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.list_primaryVariant.header().setCascadingSectionResizes(False)
        self.list_primaryVariant.header().setHighlightSections(False)
        self.button_primaryVariant = QtWidgets.QPushButton(self.page_primary)
        self.button_primaryVariant.setGeometry(QtCore.QRect(620, 120, 321, 51))
        self.button_primaryVariant.setStyleSheet("QPushButton{\n"
"    font: 63 18pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(38, 55, 62);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"    font: 63 18pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(30, 47, 54);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    font: 63 18pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(22, 39, 46);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}")
        self.button_primaryVariant.setDefault(False)
        self.button_primaryVariant.setFlat(False)
        self.button_primaryVariant.setObjectName("button_primaryVariant")
        self.radio_primary = QtWidgets.QRadioButton(self.page_primary)
        self.radio_primary.setGeometry(QtCore.QRect(1210, 60, 171, 31))
        self.radio_primary.setStyleSheet("font: 63 14pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.radio_primary.setObjectName("radio_primary")
        self.primary_fourPic_1 = QtWidgets.QLabel(self.page_primary)
        self.primary_fourPic_1.setGeometry(QtCore.QRect(546, 480, 100, 105))
        self.primary_fourPic_1.setAutoFillBackground(False)
        self.primary_fourPic_1.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.primary_fourPic_1.setText("")
        self.primary_fourPic_1.setScaledContents(True)
        self.primary_fourPic_1.setAlignment(QtCore.Qt.AlignCenter)
        self.primary_fourPic_1.setObjectName("primary_fourPic_1")
        self.primary_fourPic_2 = QtWidgets.QLabel(self.page_primary)
        self.primary_fourPic_2.setGeometry(QtCore.QRect(682, 480, 100, 105))
        self.primary_fourPic_2.setAutoFillBackground(False)
        self.primary_fourPic_2.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.primary_fourPic_2.setText("")
        self.primary_fourPic_2.setScaledContents(True)
        self.primary_fourPic_2.setAlignment(QtCore.Qt.AlignCenter)
        self.primary_fourPic_2.setObjectName("primary_fourPic_2")
        self.primary_fourPic_3 = QtWidgets.QLabel(self.page_primary)
        self.primary_fourPic_3.setGeometry(QtCore.QRect(818, 480, 100, 105))
        self.primary_fourPic_3.setAutoFillBackground(False)
        self.primary_fourPic_3.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.primary_fourPic_3.setText("")
        self.primary_fourPic_3.setScaledContents(True)
        self.primary_fourPic_3.setAlignment(QtCore.Qt.AlignCenter)
        self.primary_fourPic_3.setObjectName("primary_fourPic_3")
        self.primary_fourPic_4 = QtWidgets.QLabel(self.page_primary)
        self.primary_fourPic_4.setGeometry(QtCore.QRect(954, 480, 100, 105))
        self.primary_fourPic_4.setAutoFillBackground(False)
        self.primary_fourPic_4.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.primary_fourPic_4.setText("")
        self.primary_fourPic_4.setScaledContents(True)
        self.primary_fourPic_4.setAlignment(QtCore.Qt.AlignCenter)
        self.primary_fourPic_4.setObjectName("primary_fourPic_4")
        self.primary_fivePic_1 = QtWidgets.QLabel(self.page_primary)
        self.primary_fivePic_1.setGeometry(QtCore.QRect(523, 480, 100, 105))
        self.primary_fivePic_1.setAutoFillBackground(False)
        self.primary_fivePic_1.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.primary_fivePic_1.setText("")
        self.primary_fivePic_1.setScaledContents(True)
        self.primary_fivePic_1.setAlignment(QtCore.Qt.AlignCenter)
        self.primary_fivePic_1.setObjectName("primary_fivePic_1")
        self.primary_fivePic_2 = QtWidgets.QLabel(self.page_primary)
        self.primary_fivePic_2.setGeometry(QtCore.QRect(636, 480, 100, 105))
        self.primary_fivePic_2.setAutoFillBackground(False)
        self.primary_fivePic_2.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.primary_fivePic_2.setText("")
        self.primary_fivePic_2.setScaledContents(True)
        self.primary_fivePic_2.setAlignment(QtCore.Qt.AlignCenter)
        self.primary_fivePic_2.setObjectName("primary_fivePic_2")
        self.primary_fivePic_3 = QtWidgets.QLabel(self.page_primary)
        self.primary_fivePic_3.setGeometry(QtCore.QRect(749, 480, 100, 105))
        self.primary_fivePic_3.setAutoFillBackground(False)
        self.primary_fivePic_3.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.primary_fivePic_3.setText("")
        self.primary_fivePic_3.setScaledContents(True)
        self.primary_fivePic_3.setAlignment(QtCore.Qt.AlignCenter)
        self.primary_fivePic_3.setObjectName("primary_fivePic_3")
        self.primary_fivePic_4 = QtWidgets.QLabel(self.page_primary)
        self.primary_fivePic_4.setGeometry(QtCore.QRect(862, 480, 100, 105))
        self.primary_fivePic_4.setAutoFillBackground(False)
        self.primary_fivePic_4.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.primary_fivePic_4.setText("")
        self.primary_fivePic_4.setScaledContents(True)
        self.primary_fivePic_4.setAlignment(QtCore.Qt.AlignCenter)
        self.primary_fivePic_4.setObjectName("primary_fivePic_4")
        self.primary_fivePic_5 = QtWidgets.QLabel(self.page_primary)
        self.primary_fivePic_5.setGeometry(QtCore.QRect(975, 480, 100, 105))
        self.primary_fivePic_5.setAutoFillBackground(False)
        self.primary_fivePic_5.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.primary_fivePic_5.setText("")
        self.primary_fivePic_5.setScaledContents(True)
        self.primary_fivePic_5.setAlignment(QtCore.Qt.AlignCenter)
        self.primary_fivePic_5.setObjectName("primary_fivePic_5")
        self.primary_normalPic = QtWidgets.QLabel(self.page_primary)
        self.primary_normalPic.setGeometry(QtCore.QRect(225, 440, 120, 140))
        self.primary_normalPic.setAutoFillBackground(False)
        self.primary_normalPic.setStyleSheet("font: 63 11pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.primary_normalPic.setText("")
        self.primary_normalPic.setScaledContents(True)
        self.primary_normalPic.setAlignment(QtCore.Qt.AlignCenter)
        self.primary_normalPic.setObjectName("primary_normalPic")
        self.primary_primePic = QtWidgets.QLabel(self.page_primary)
        self.primary_primePic.setGeometry(QtCore.QRect(1255, 440, 120, 140))
        self.primary_primePic.setAutoFillBackground(False)
        self.primary_primePic.setStyleSheet("font: 63 11pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.primary_primePic.setText("")
        self.primary_primePic.setScaledContents(True)
        self.primary_primePic.setAlignment(QtCore.Qt.AlignCenter)
        self.primary_primePic.setObjectName("primary_primePic")
        self.stackedWidget.addWidget(self.page_primary)
        self.page_secondary = QtWidgets.QWidget()
        self.page_secondary.setObjectName("page_secondary")
        self.line_secondarySelect = QtWidgets.QLineEdit(self.page_secondary)
        self.line_secondarySelect.setGeometry(QtCore.QRect(460, 60, 680, 31))
        self.line_secondarySelect.setAutoFillBackground(False)
        self.line_secondarySelect.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px\n"
"")
        self.line_secondarySelect.setText("")
        self.line_secondarySelect.setAlignment(QtCore.Qt.AlignCenter)
        self.line_secondarySelect.setObjectName("line_secondarySelect")
        self.label_secondary = QtWidgets.QLabel(self.page_secondary)
        self.label_secondary.setGeometry(QtCore.QRect(500, 0, 600, 60))
        self.label_secondary.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.label_secondary.setAlignment(QtCore.Qt.AlignCenter)
        self.label_secondary.setObjectName("label_secondary")
        self.label_secondaryMiddle = QtWidgets.QLabel(self.page_secondary)
        self.label_secondaryMiddle.setGeometry(QtCore.QRect(510, 190, 580, 400))
        self.label_secondaryMiddle.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(49, 72, 80);\n"
"color: rgb(180, 180, 180);\n"
"padding: 8px")
        self.label_secondaryMiddle.setText("")
        self.label_secondaryMiddle.setScaledContents(True)
        self.label_secondaryMiddle.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_secondaryMiddle.setWordWrap(True)
        self.label_secondaryMiddle.setObjectName("label_secondaryMiddle")
        self.label_secondaryRight = QtWidgets.QLabel(self.page_secondary)
        self.label_secondaryRight.setGeometry(QtCore.QRect(1090, 190, 450, 400))
        self.label_secondaryRight.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(49, 72, 80);\n"
"color: rgb(180, 180, 180);\n"
"padding: 8px")
        self.label_secondaryRight.setText("")
        self.label_secondaryRight.setScaledContents(True)
        self.label_secondaryRight.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_secondaryRight.setWordWrap(True)
        self.label_secondaryRight.setObjectName("label_secondaryRight")
        self.label_secondaryLeft = QtWidgets.QLabel(self.page_secondary)
        self.label_secondaryLeft.setGeometry(QtCore.QRect(60, 190, 450, 400))
        self.label_secondaryLeft.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(49, 72, 80);\n"
"color: rgb(180, 180, 180);\n"
"padding: 8px")
        self.label_secondaryLeft.setText("")
        self.label_secondaryLeft.setScaledContents(True)
        self.label_secondaryLeft.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_secondaryLeft.setWordWrap(True)
        self.label_secondaryLeft.setObjectName("label_secondaryLeft")
        self.label_secondaryMastery = QtWidgets.QLabel(self.page_secondary)
        self.label_secondaryMastery.setGeometry(QtCore.QRect(60, 590, 1480, 80))
        self.label_secondaryMastery.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(49, 72, 80);\n"
"color: rgb(180, 180, 180);")
        self.label_secondaryMastery.setText("")
        self.label_secondaryMastery.setAlignment(QtCore.Qt.AlignCenter)
        self.label_secondaryMastery.setObjectName("label_secondaryMastery")
        self.list_secondaryVariant = QtWidgets.QTreeWidget(self.page_secondary)
        self.list_secondaryVariant.setGeometry(QtCore.QRect(50, 20, 331, 151))
        self.list_secondaryVariant.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"border-radius: 10px")
        self.list_secondaryVariant.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list_secondaryVariant.setAlternatingRowColors(False)
        self.list_secondaryVariant.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.list_secondaryVariant.setObjectName("list_secondaryVariant")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.list_secondaryVariant.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_secondaryVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_secondaryVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_secondaryVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_secondaryVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_secondaryVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_secondaryVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.list_secondaryVariant.header().setCascadingSectionResizes(False)
        self.list_secondaryVariant.header().setHighlightSections(False)
        self.button_secondaryVariant = QtWidgets.QPushButton(self.page_secondary)
        self.button_secondaryVariant.setGeometry(QtCore.QRect(620, 120, 321, 51))
        self.button_secondaryVariant.setStyleSheet("QPushButton{\n"
"    font: 63 14pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(38, 55, 62);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"    font: 63 14pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(30, 47, 54);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    font: 63 14pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(22, 39, 46);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}")
        self.button_secondaryVariant.setDefault(False)
        self.button_secondaryVariant.setFlat(False)
        self.button_secondaryVariant.setObjectName("button_secondaryVariant")
        self.radio_secondary = QtWidgets.QRadioButton(self.page_secondary)
        self.radio_secondary.setGeometry(QtCore.QRect(1210, 60, 171, 31))
        self.radio_secondary.setStyleSheet("font: 63 14pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.radio_secondary.setObjectName("radio_secondary")
        self.secondary_threePic_1 = QtWidgets.QLabel(self.page_secondary)
        self.secondary_threePic_1.setGeometry(QtCore.QRect(580, 480, 100, 105))
        self.secondary_threePic_1.setAutoFillBackground(False)
        self.secondary_threePic_1.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.secondary_threePic_1.setText("")
        self.secondary_threePic_1.setScaledContents(True)
        self.secondary_threePic_1.setAlignment(QtCore.Qt.AlignCenter)
        self.secondary_threePic_1.setObjectName("secondary_threePic_1")
        self.secondary_threePic_2 = QtWidgets.QLabel(self.page_secondary)
        self.secondary_threePic_2.setGeometry(QtCore.QRect(750, 480, 100, 105))
        self.secondary_threePic_2.setAutoFillBackground(False)
        self.secondary_threePic_2.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.secondary_threePic_2.setText("")
        self.secondary_threePic_2.setScaledContents(True)
        self.secondary_threePic_2.setAlignment(QtCore.Qt.AlignCenter)
        self.secondary_threePic_2.setObjectName("secondary_threePic_2")
        self.secondary_threePic_3 = QtWidgets.QLabel(self.page_secondary)
        self.secondary_threePic_3.setGeometry(QtCore.QRect(920, 480, 100, 105))
        self.secondary_threePic_3.setAutoFillBackground(False)
        self.secondary_threePic_3.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.secondary_threePic_3.setText("")
        self.secondary_threePic_3.setScaledContents(True)
        self.secondary_threePic_3.setAlignment(QtCore.Qt.AlignCenter)
        self.secondary_threePic_3.setObjectName("secondary_threePic_3")
        self.secondary_fourPic_1 = QtWidgets.QLabel(self.page_secondary)
        self.secondary_fourPic_1.setGeometry(QtCore.QRect(546, 480, 100, 105))
        self.secondary_fourPic_1.setAutoFillBackground(False)
        self.secondary_fourPic_1.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.secondary_fourPic_1.setText("")
        self.secondary_fourPic_1.setScaledContents(True)
        self.secondary_fourPic_1.setAlignment(QtCore.Qt.AlignCenter)
        self.secondary_fourPic_1.setObjectName("secondary_fourPic_1")
        self.secondary_fourPic_2 = QtWidgets.QLabel(self.page_secondary)
        self.secondary_fourPic_2.setGeometry(QtCore.QRect(682, 480, 100, 105))
        self.secondary_fourPic_2.setAutoFillBackground(False)
        self.secondary_fourPic_2.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.secondary_fourPic_2.setText("")
        self.secondary_fourPic_2.setScaledContents(True)
        self.secondary_fourPic_2.setAlignment(QtCore.Qt.AlignCenter)
        self.secondary_fourPic_2.setObjectName("secondary_fourPic_2")
        self.secondary_fourPic_3 = QtWidgets.QLabel(self.page_secondary)
        self.secondary_fourPic_3.setGeometry(QtCore.QRect(818, 480, 100, 105))
        self.secondary_fourPic_3.setAutoFillBackground(False)
        self.secondary_fourPic_3.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.secondary_fourPic_3.setText("")
        self.secondary_fourPic_3.setScaledContents(True)
        self.secondary_fourPic_3.setAlignment(QtCore.Qt.AlignCenter)
        self.secondary_fourPic_3.setObjectName("secondary_fourPic_3")
        self.secondary_fourPic_4 = QtWidgets.QLabel(self.page_secondary)
        self.secondary_fourPic_4.setGeometry(QtCore.QRect(954, 480, 100, 105))
        self.secondary_fourPic_4.setAutoFillBackground(False)
        self.secondary_fourPic_4.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.secondary_fourPic_4.setText("")
        self.secondary_fourPic_4.setScaledContents(True)
        self.secondary_fourPic_4.setAlignment(QtCore.Qt.AlignCenter)
        self.secondary_fourPic_4.setObjectName("secondary_fourPic_4")
        self.secondary_fivePic_1 = QtWidgets.QLabel(self.page_secondary)
        self.secondary_fivePic_1.setGeometry(QtCore.QRect(523, 480, 100, 105))
        self.secondary_fivePic_1.setAutoFillBackground(False)
        self.secondary_fivePic_1.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.secondary_fivePic_1.setText("")
        self.secondary_fivePic_1.setScaledContents(True)
        self.secondary_fivePic_1.setAlignment(QtCore.Qt.AlignCenter)
        self.secondary_fivePic_1.setObjectName("secondary_fivePic_1")
        self.secondary_fivePic_2 = QtWidgets.QLabel(self.page_secondary)
        self.secondary_fivePic_2.setGeometry(QtCore.QRect(636, 480, 100, 105))
        self.secondary_fivePic_2.setAutoFillBackground(False)
        self.secondary_fivePic_2.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.secondary_fivePic_2.setText("")
        self.secondary_fivePic_2.setScaledContents(True)
        self.secondary_fivePic_2.setAlignment(QtCore.Qt.AlignCenter)
        self.secondary_fivePic_2.setObjectName("secondary_fivePic_2")
        self.secondary_fivePic_3 = QtWidgets.QLabel(self.page_secondary)
        self.secondary_fivePic_3.setGeometry(QtCore.QRect(749, 480, 100, 105))
        self.secondary_fivePic_3.setAutoFillBackground(False)
        self.secondary_fivePic_3.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.secondary_fivePic_3.setText("")
        self.secondary_fivePic_3.setScaledContents(True)
        self.secondary_fivePic_3.setAlignment(QtCore.Qt.AlignCenter)
        self.secondary_fivePic_3.setObjectName("secondary_fivePic_3")
        self.secondary_fivePic_4 = QtWidgets.QLabel(self.page_secondary)
        self.secondary_fivePic_4.setGeometry(QtCore.QRect(862, 480, 100, 105))
        self.secondary_fivePic_4.setAutoFillBackground(False)
        self.secondary_fivePic_4.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.secondary_fivePic_4.setText("")
        self.secondary_fivePic_4.setScaledContents(True)
        self.secondary_fivePic_4.setAlignment(QtCore.Qt.AlignCenter)
        self.secondary_fivePic_4.setObjectName("secondary_fivePic_4")
        self.secondary_fivePic_5 = QtWidgets.QLabel(self.page_secondary)
        self.secondary_fivePic_5.setGeometry(QtCore.QRect(975, 480, 100, 105))
        self.secondary_fivePic_5.setAutoFillBackground(False)
        self.secondary_fivePic_5.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.secondary_fivePic_5.setText("")
        self.secondary_fivePic_5.setScaledContents(True)
        self.secondary_fivePic_5.setAlignment(QtCore.Qt.AlignCenter)
        self.secondary_fivePic_5.setObjectName("secondary_fivePic_5")
        self.secondary_normalPic = QtWidgets.QLabel(self.page_secondary)
        self.secondary_normalPic.setGeometry(QtCore.QRect(225, 440, 120, 140))
        self.secondary_normalPic.setAutoFillBackground(False)
        self.secondary_normalPic.setStyleSheet("font: 63 11pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.secondary_normalPic.setText("")
        self.secondary_normalPic.setScaledContents(True)
        self.secondary_normalPic.setAlignment(QtCore.Qt.AlignCenter)
        self.secondary_normalPic.setObjectName("secondary_normalPic")
        self.secondary_primePic = QtWidgets.QLabel(self.page_secondary)
        self.secondary_primePic.setGeometry(QtCore.QRect(1255, 440, 120, 140))
        self.secondary_primePic.setAutoFillBackground(False)
        self.secondary_primePic.setStyleSheet("font: 63 11pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.secondary_primePic.setText("")
        self.secondary_primePic.setScaledContents(True)
        self.secondary_primePic.setAlignment(QtCore.Qt.AlignCenter)
        self.secondary_primePic.setObjectName("secondary_primePic")
        self.stackedWidget.addWidget(self.page_secondary)
        self.page_melee = QtWidgets.QWidget()
        self.page_melee.setObjectName("page_melee")
        self.label_melee = QtWidgets.QLabel(self.page_melee)
        self.label_melee.setGeometry(QtCore.QRect(500, 0, 600, 60))
        self.label_melee.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.label_melee.setAlignment(QtCore.Qt.AlignCenter)
        self.label_melee.setObjectName("label_melee")
        self.line_meleeSelect = QtWidgets.QLineEdit(self.page_melee)
        self.line_meleeSelect.setGeometry(QtCore.QRect(460, 60, 680, 31))
        self.line_meleeSelect.setAutoFillBackground(False)
        self.line_meleeSelect.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px\n"
"")
        self.line_meleeSelect.setText("")
        self.line_meleeSelect.setAlignment(QtCore.Qt.AlignCenter)
        self.line_meleeSelect.setObjectName("line_meleeSelect")
        self.label_meleeMiddle = QtWidgets.QLabel(self.page_melee)
        self.label_meleeMiddle.setGeometry(QtCore.QRect(510, 190, 580, 400))
        self.label_meleeMiddle.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(49, 72, 80);\n"
"color: rgb(180, 180, 180);\n"
"padding: 8px")
        self.label_meleeMiddle.setText("")
        self.label_meleeMiddle.setScaledContents(True)
        self.label_meleeMiddle.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_meleeMiddle.setWordWrap(True)
        self.label_meleeMiddle.setObjectName("label_meleeMiddle")
        self.label_meleeRight = QtWidgets.QLabel(self.page_melee)
        self.label_meleeRight.setGeometry(QtCore.QRect(1090, 190, 450, 400))
        self.label_meleeRight.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(49, 72, 80);\n"
"color: rgb(180, 180, 180);\n"
"padding: 8px")
        self.label_meleeRight.setText("")
        self.label_meleeRight.setScaledContents(True)
        self.label_meleeRight.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_meleeRight.setWordWrap(True)
        self.label_meleeRight.setObjectName("label_meleeRight")
        self.label_meleeLeft = QtWidgets.QLabel(self.page_melee)
        self.label_meleeLeft.setGeometry(QtCore.QRect(60, 190, 450, 400))
        self.label_meleeLeft.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(49, 72, 80);\n"
"color: rgb(180, 180, 180);\n"
"padding: 8px")
        self.label_meleeLeft.setText("")
        self.label_meleeLeft.setScaledContents(True)
        self.label_meleeLeft.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_meleeLeft.setWordWrap(True)
        self.label_meleeLeft.setObjectName("label_meleeLeft")
        self.label_meleeMastery = QtWidgets.QLabel(self.page_melee)
        self.label_meleeMastery.setGeometry(QtCore.QRect(60, 590, 1480, 80))
        self.label_meleeMastery.setStyleSheet("font: 63 22pt \"Segoe UI Semibold\";\n"
"background-color: rgb(49, 72, 80);\n"
"color: rgb(180, 180, 180);")
        self.label_meleeMastery.setText("")
        self.label_meleeMastery.setAlignment(QtCore.Qt.AlignCenter)
        self.label_meleeMastery.setObjectName("label_meleeMastery")
        self.radio_melee = QtWidgets.QRadioButton(self.page_melee)
        self.radio_melee.setGeometry(QtCore.QRect(1210, 60, 171, 31))
        self.radio_melee.setStyleSheet("font: 63 14pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.radio_melee.setObjectName("radio_melee")
        self.button_meleeVariant = QtWidgets.QPushButton(self.page_melee)
        self.button_meleeVariant.setGeometry(QtCore.QRect(620, 120, 321, 51))
        self.button_meleeVariant.setStyleSheet("QPushButton{\n"
"    font: 63 18pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(38, 55, 62);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"    font: 63 18pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(30, 47, 54);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    font: 63 18pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(22, 39, 46);\n"
"    color: rgb(180, 180, 180);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 1px solid rgb(0,0,0);\n"
"    border-right: 1px solid rgb(0,0,0);\n"
"    border-bottom: 3px solid rgb(0,0,0);\n"
"}")
        self.button_meleeVariant.setDefault(False)
        self.button_meleeVariant.setFlat(False)
        self.button_meleeVariant.setObjectName("button_meleeVariant")
        self.list_meleeVariant = QtWidgets.QTreeWidget(self.page_melee)
        self.list_meleeVariant.setGeometry(QtCore.QRect(50, 20, 331, 151))
        self.list_meleeVariant.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"border-radius: 10px")
        self.list_meleeVariant.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list_meleeVariant.setAlternatingRowColors(False)
        self.list_meleeVariant.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.list_meleeVariant.setObjectName("list_meleeVariant")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.list_meleeVariant.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_meleeVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_meleeVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_meleeVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_meleeVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_meleeVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.list_meleeVariant)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.list_meleeVariant.header().setCascadingSectionResizes(False)
        self.list_meleeVariant.header().setHighlightSections(False)
        self.melee_threePic_1 = QtWidgets.QLabel(self.page_melee)
        self.melee_threePic_1.setGeometry(QtCore.QRect(580, 480, 100, 105))
        self.melee_threePic_1.setAutoFillBackground(False)
        self.melee_threePic_1.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.melee_threePic_1.setText("")
        self.melee_threePic_1.setScaledContents(True)
        self.melee_threePic_1.setAlignment(QtCore.Qt.AlignCenter)
        self.melee_threePic_1.setObjectName("melee_threePic_1")
        self.melee_threePic_2 = QtWidgets.QLabel(self.page_melee)
        self.melee_threePic_2.setGeometry(QtCore.QRect(750, 480, 100, 105))
        self.melee_threePic_2.setAutoFillBackground(False)
        self.melee_threePic_2.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.melee_threePic_2.setText("")
        self.melee_threePic_2.setScaledContents(True)
        self.melee_threePic_2.setAlignment(QtCore.Qt.AlignCenter)
        self.melee_threePic_2.setObjectName("melee_threePic_2")
        self.melee_threePic_3 = QtWidgets.QLabel(self.page_melee)
        self.melee_threePic_3.setGeometry(QtCore.QRect(920, 480, 100, 105))
        self.melee_threePic_3.setAutoFillBackground(False)
        self.melee_threePic_3.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.melee_threePic_3.setText("")
        self.melee_threePic_3.setScaledContents(True)
        self.melee_threePic_3.setAlignment(QtCore.Qt.AlignCenter)
        self.melee_threePic_3.setObjectName("melee_threePic_3")
        self.melee_fourPic_1 = QtWidgets.QLabel(self.page_melee)
        self.melee_fourPic_1.setGeometry(QtCore.QRect(546, 480, 100, 105))
        self.melee_fourPic_1.setAutoFillBackground(False)
        self.melee_fourPic_1.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.melee_fourPic_1.setText("")
        self.melee_fourPic_1.setScaledContents(True)
        self.melee_fourPic_1.setAlignment(QtCore.Qt.AlignCenter)
        self.melee_fourPic_1.setObjectName("melee_fourPic_1")
        self.melee_fourPic_2 = QtWidgets.QLabel(self.page_melee)
        self.melee_fourPic_2.setGeometry(QtCore.QRect(682, 480, 100, 105))
        self.melee_fourPic_2.setAutoFillBackground(False)
        self.melee_fourPic_2.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.melee_fourPic_2.setText("")
        self.melee_fourPic_2.setScaledContents(True)
        self.melee_fourPic_2.setAlignment(QtCore.Qt.AlignCenter)
        self.melee_fourPic_2.setObjectName("melee_fourPic_2")
        self.melee_fourPic_3 = QtWidgets.QLabel(self.page_melee)
        self.melee_fourPic_3.setGeometry(QtCore.QRect(818, 480, 100, 105))
        self.melee_fourPic_3.setAutoFillBackground(False)
        self.melee_fourPic_3.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.melee_fourPic_3.setText("")
        self.melee_fourPic_3.setScaledContents(True)
        self.melee_fourPic_3.setAlignment(QtCore.Qt.AlignCenter)
        self.melee_fourPic_3.setObjectName("melee_fourPic_3")
        self.melee_fourPic_4 = QtWidgets.QLabel(self.page_melee)
        self.melee_fourPic_4.setGeometry(QtCore.QRect(954, 480, 100, 105))
        self.melee_fourPic_4.setAutoFillBackground(False)
        self.melee_fourPic_4.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.melee_fourPic_4.setText("")
        self.melee_fourPic_4.setScaledContents(True)
        self.melee_fourPic_4.setAlignment(QtCore.Qt.AlignCenter)
        self.melee_fourPic_4.setObjectName("melee_fourPic_4")
        self.melee_normalPic = QtWidgets.QLabel(self.page_melee)
        self.melee_normalPic.setGeometry(QtCore.QRect(225, 440, 120, 140))
        self.melee_normalPic.setAutoFillBackground(False)
        self.melee_normalPic.setStyleSheet("font: 63 11pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.melee_normalPic.setText("")
        self.melee_normalPic.setScaledContents(True)
        self.melee_normalPic.setAlignment(QtCore.Qt.AlignCenter)
        self.melee_normalPic.setObjectName("melee_normalPic")
        self.melee_primePic = QtWidgets.QLabel(self.page_melee)
        self.melee_primePic.setGeometry(QtCore.QRect(1255, 440, 120, 140))
        self.melee_primePic.setAutoFillBackground(False)
        self.melee_primePic.setStyleSheet("font: 63 11pt \"Segoe UI Semibold\";\n"
"color: rgb(180, 180, 180);")
        self.melee_primePic.setText("")
        self.melee_primePic.setScaledContents(True)
        self.melee_primePic.setAlignment(QtCore.Qt.AlignCenter)
        self.melee_primePic.setObjectName("melee_primePic")
        self.stackedWidget.addWidget(self.page_melee)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Tracker"))
        self.button_warframe.setText(_translate("MainWindow", "Warframes"))
        self.button_primary.setText(_translate("MainWindow", "Primary"))
        self.button_secondary.setText(_translate("MainWindow", "Secondary"))
        self.button_melee.setText(_translate("MainWindow", "Melee"))
        self.button_clearPage.setText(_translate("MainWindow", "Clear Page"))
        self.button_clearAll.setText(_translate("MainWindow", "Clear All"))
        self.label_warframe.setText(_translate("MainWindow", "Select your Warframe"))
        self.label_primary.setText(_translate("MainWindow", "Select your Primary Weapon"))
        self.list_primaryVariant.setSortingEnabled(False)
        self.list_primaryVariant.headerItem().setText(0, _translate("MainWindow", "Primary Weapon Variants"))
        __sortingEnabled = self.list_primaryVariant.isSortingEnabled()
        self.list_primaryVariant.setSortingEnabled(False)
        self.list_primaryVariant.topLevelItem(0).setText(0, _translate("MainWindow", "Kuva"))
        self.list_primaryVariant.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Bramma"))
        self.list_primaryVariant.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Chakkhurr"))
        self.list_primaryVariant.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Drakgoon"))
        self.list_primaryVariant.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "Hek"))
        self.list_primaryVariant.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "Hind"))
        self.list_primaryVariant.topLevelItem(0).child(5).setText(0, _translate("MainWindow", "Karak"))
        self.list_primaryVariant.topLevelItem(0).child(6).setText(0, _translate("MainWindow", "Kohm"))
        self.list_primaryVariant.topLevelItem(0).child(7).setText(0, _translate("MainWindow", "Ogris"))
        self.list_primaryVariant.topLevelItem(0).child(8).setText(0, _translate("MainWindow", "Quartakk"))
        self.list_primaryVariant.topLevelItem(0).child(9).setText(0, _translate("MainWindow", "Tonkor"))
        self.list_primaryVariant.topLevelItem(0).child(10).setText(0, _translate("MainWindow", "Zarr"))
        self.list_primaryVariant.topLevelItem(1).setText(0, _translate("MainWindow", "Tenet"))
        self.list_primaryVariant.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Arca Plasmor"))
        self.list_primaryVariant.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Envoy"))
        self.list_primaryVariant.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "Flux Rifle"))
        self.list_primaryVariant.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "Tetra"))
        self.list_primaryVariant.topLevelItem(2).setText(0, _translate("MainWindow", "Wraith"))
        self.list_primaryVariant.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Gorgon"))
        self.list_primaryVariant.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "Ignis"))
        self.list_primaryVariant.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "Karak"))
        self.list_primaryVariant.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "Latron"))
        self.list_primaryVariant.topLevelItem(2).child(4).setText(0, _translate("MainWindow", "Strun"))
        self.list_primaryVariant.topLevelItem(2).child(5).setText(0, _translate("MainWindow", "Vulkar"))
        self.list_primaryVariant.topLevelItem(3).setText(0, _translate("MainWindow", "Vandal"))
        self.list_primaryVariant.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "Braton"))
        self.list_primaryVariant.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "Dera"))
        self.list_primaryVariant.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "Glaxion"))
        self.list_primaryVariant.topLevelItem(3).child(3).setText(0, _translate("MainWindow", "Opticor"))
        self.list_primaryVariant.topLevelItem(3).child(4).setText(0, _translate("MainWindow", "Quanta"))
        self.list_primaryVariant.topLevelItem(3).child(5).setText(0, _translate("MainWindow", "Snipetron"))
        self.list_primaryVariant.topLevelItem(3).child(6).setText(0, _translate("MainWindow", "Supra"))
        self.list_primaryVariant.topLevelItem(4).setText(0, _translate("MainWindow", "Prisma"))
        self.list_primaryVariant.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "Gorgon"))
        self.list_primaryVariant.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "Grakata"))
        self.list_primaryVariant.topLevelItem(4).child(2).setText(0, _translate("MainWindow", "Grinlok"))
        self.list_primaryVariant.topLevelItem(4).child(3).setText(0, _translate("MainWindow", "Tetra"))
        self.list_primaryVariant.topLevelItem(5).setText(0, _translate("MainWindow", "Misc Variants"))
        self.list_primaryVariant.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "Carmine Penta"))
        self.list_primaryVariant.topLevelItem(5).child(1).setText(0, _translate("MainWindow", "Dex Sybaris"))
        self.list_primaryVariant.topLevelItem(5).child(2).setText(0, _translate("MainWindow", "MK1-Braton"))
        self.list_primaryVariant.topLevelItem(5).child(3).setText(0, _translate("MainWindow", "MK1-Paris"))
        self.list_primaryVariant.topLevelItem(5).child(4).setText(0, _translate("MainWindow", "MK1-Strun"))
        self.list_primaryVariant.topLevelItem(5).child(5).setText(0, _translate("MainWindow", "Mutalist Cernos"))
        self.list_primaryVariant.topLevelItem(5).child(6).setText(0, _translate("MainWindow", "Mutalist Quanta"))
        self.list_primaryVariant.topLevelItem(5).child(7).setText(0, _translate("MainWindow", "Proboscis Cernos"))
        self.list_primaryVariant.topLevelItem(5).child(8).setText(0, _translate("MainWindow", "Rakta Cernos"))
        self.list_primaryVariant.topLevelItem(5).child(9).setText(0, _translate("MainWindow", "Sancti Tigris"))
        self.list_primaryVariant.topLevelItem(5).child(10).setText(0, _translate("MainWindow", "Secura Penta"))
        self.list_primaryVariant.topLevelItem(5).child(11).setText(0, _translate("MainWindow", "Synoid Simulor"))
        self.list_primaryVariant.topLevelItem(5).child(12).setText(0, _translate("MainWindow", "Telos Boltor"))
        self.list_primaryVariant.topLevelItem(5).child(13).setText(0, _translate("MainWindow", "Vaykor Hek"))
        self.list_primaryVariant.setSortingEnabled(__sortingEnabled)
        self.button_primaryVariant.setText(_translate("MainWindow", "Find selected primary variant"))
        self.radio_primary.setText(_translate("MainWindow", "Show variant list"))
        self.label_secondary.setText(_translate("MainWindow", "Select your Secondary Weapon"))
        self.list_secondaryVariant.setSortingEnabled(False)
        self.list_secondaryVariant.headerItem().setText(0, _translate("MainWindow", "Secondary Weapon Variants"))
        __sortingEnabled = self.list_secondaryVariant.isSortingEnabled()
        self.list_secondaryVariant.setSortingEnabled(False)
        self.list_secondaryVariant.topLevelItem(0).setText(0, _translate("MainWindow", "Kuva"))
        self.list_secondaryVariant.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Brakk"))
        self.list_secondaryVariant.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Kraken"))
        self.list_secondaryVariant.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Nukor"))
        self.list_secondaryVariant.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "Seer"))
        self.list_secondaryVariant.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "Twin Stubbas"))
        self.list_secondaryVariant.topLevelItem(1).setText(0, _translate("MainWindow", "Tenet"))
        self.list_secondaryVariant.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Cycron"))
        self.list_secondaryVariant.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Detron"))
        self.list_secondaryVariant.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "Diplos"))
        self.list_secondaryVariant.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "Spirex"))
        self.list_secondaryVariant.topLevelItem(2).setText(0, _translate("MainWindow", "Wraith"))
        self.list_secondaryVariant.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Viper"))
        self.list_secondaryVariant.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "Twin Vipers"))
        self.list_secondaryVariant.topLevelItem(3).setText(0, _translate("MainWindow", "Vandal"))
        self.list_secondaryVariant.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "Lato"))
        self.list_secondaryVariant.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "Spectra"))
        self.list_secondaryVariant.topLevelItem(4).setText(0, _translate("MainWindow", "Prisma"))
        self.list_secondaryVariant.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "Angstrum"))
        self.list_secondaryVariant.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "Twin Gremlins"))
        self.list_secondaryVariant.topLevelItem(5).setText(0, _translate("MainWindow", "Twin"))
        self.list_secondaryVariant.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "Grakatas"))
        self.list_secondaryVariant.topLevelItem(5).child(1).setText(0, _translate("MainWindow", "Gremlins"))
        self.list_secondaryVariant.topLevelItem(5).child(2).setText(0, _translate("MainWindow", "Kohmak"))
        self.list_secondaryVariant.topLevelItem(5).child(3).setText(0, _translate("MainWindow", "Rogga"))
        self.list_secondaryVariant.topLevelItem(5).child(4).setText(0, _translate("MainWindow", "Vipers"))
        self.list_secondaryVariant.setSortingEnabled(__sortingEnabled)
        self.button_secondaryVariant.setText(_translate("MainWindow", "Find selected secondary variant"))
        self.radio_secondary.setText(_translate("MainWindow", "Show variant list"))
        self.label_melee.setText(_translate("MainWindow", "Select your Melee Weapon"))
        self.radio_melee.setText(_translate("MainWindow", "Show variant list"))
        self.button_meleeVariant.setText(_translate("MainWindow", "Find selected melee variant"))
        self.list_meleeVariant.setSortingEnabled(False)
        self.list_meleeVariant.headerItem().setText(0, _translate("MainWindow", "Melee Weapon Variants"))
        __sortingEnabled = self.list_meleeVariant.isSortingEnabled()
        self.list_meleeVariant.setSortingEnabled(False)
        self.list_meleeVariant.topLevelItem(0).setText(0, _translate("MainWindow", "Kuva"))
        self.list_meleeVariant.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Shildeg"))
        self.list_meleeVariant.topLevelItem(1).setText(0, _translate("MainWindow", "Tenet"))
        self.list_meleeVariant.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Agendus"))
        self.list_meleeVariant.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Exec"))
        self.list_meleeVariant.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "Grigori"))
        self.list_meleeVariant.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "Livia"))
        self.list_meleeVariant.topLevelItem(2).setText(0, _translate("MainWindow", "Wraith"))
        self.list_meleeVariant.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Halikar"))
        self.list_meleeVariant.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "Machete"))
        self.list_meleeVariant.topLevelItem(3).setText(0, _translate("MainWindow", "Vandal"))
        self.list_meleeVariant.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "Prova"))
        self.list_meleeVariant.topLevelItem(4).setText(0, _translate("MainWindow", "Prisma"))
        self.list_meleeVariant.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "Dual Cleavers"))
        self.list_meleeVariant.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "Machete"))
        self.list_meleeVariant.topLevelItem(4).child(2).setText(0, _translate("MainWindow", "Obex"))
        self.list_meleeVariant.topLevelItem(4).child(3).setText(0, _translate("MainWindow", "Skana"))
        self.list_meleeVariant.topLevelItem(5).setText(0, _translate("MainWindow", "Misc Variants"))
        self.list_meleeVariant.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "Dark Split-Sword (Dual Swords)"))
        self.list_meleeVariant.topLevelItem(5).child(1).setText(0, _translate("MainWindow", "Dark Split-Sword (Heavy Blade)"))
        self.list_meleeVariant.topLevelItem(5).child(2).setText(0, _translate("MainWindow", "Dex Dakra"))
        self.list_meleeVariant.topLevelItem(5).child(3).setText(0, _translate("MainWindow", "MK1-Bo"))
        self.list_meleeVariant.topLevelItem(5).child(4).setText(0, _translate("MainWindow", "MK1-Furax"))
        self.list_meleeVariant.topLevelItem(5).child(5).setText(0, _translate("MainWindow", "Rakta Dark Dagger"))
        self.list_meleeVariant.topLevelItem(5).child(6).setText(0, _translate("MainWindow", "Sancti Magistar"))
        self.list_meleeVariant.topLevelItem(5).child(7).setText(0, _translate("MainWindow", "Synoid Heliocor"))
        self.list_meleeVariant.topLevelItem(5).child(8).setText(0, _translate("MainWindow", "Telos Boltace"))
        self.list_meleeVariant.topLevelItem(5).child(9).setText(0, _translate("MainWindow", "Vaykor Sydon"))
        self.list_meleeVariant.setSortingEnabled(__sortingEnabled)

        self.list_primaryVariant.setHidden(True)
        self.list_secondaryVariant.setHidden(True)
        self.list_meleeVariant.setHidden(True)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
